hydra:
  run:
    dir: .

defaults:
  - _self_
  - dataset@test_dataset: shrq_aerial

task_name: test

accelerator: gpu
devices: [0]
initialization_seed: 1
num_workers: 4

drop_rate: 0.5
test_batch_size: 1

patch_size: 32
train_rate: 0.8
use_augmentation: false

ckpt_path: ./repository/shrq_aerial_srocc=0.9767.ckpt
save_path: null  # default: logger.log_dir

test_only: true
test_other_dataset: false


